Lint/fix

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -11,8 +11,8 @@ source "${plugin_dir}/lib/utils.bash"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 if ! has_standalone; then
-    echo "No standalone releases are available for $ARCH"
-    exit 1
+	echo "No standalone releases are available for $ARCH"
+	exit 1
 fi
 
 release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.$STANDALONE_ARCHIVE_FORMAT"
@@ -20,9 +20,9 @@ release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.$STANDALONE_A
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 if [[ "$STANDALONE_ARCHIVE_FORMAT" = tar.gz ]]; then
-    tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+	tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
 else
-    unzip -d "$ASDF_DOWNLOAD_PATH" -o "$release_file"
+	unzip -d "$ASDF_DOWNLOAD_PATH" -o "$release_file"
 fi
 
 rm "$release_file"
