Make it work

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,19 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+if ! has_standalone; then
+    echo "No standalone releases are available for $ARCH"
+    exit 1
+fi
 
-# Download tar.gz file to the download directory
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.$STANDALONE_ARCHIVE_FORMAT"
+
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+if [[ "$STANDALONE_ARCHIVE_FORMAT" = tar.gz ]]; then
+    tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+else
+    unzip -d "$ASDF_DOWNLOAD_PATH" -o "$release_file"
+fi
 
-# Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
